# https://taskfile.dev

version: "3"

vars:
  DOCKER_IMAGE: ghcr.io/adrianliechti/loop-code

tasks:
  push:
    run: once
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:dind stacks/dind/ -f stacks/dind/Dockerfile

  push-stacks:
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:dotnet stacks/dotnet/ -f stacks/dotnet/Dockerfile
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:dotnet-dind stacks/dotnet/ -f stacks/dotnet/Dockerfile --build-arg CODE_IMAGE=ghcr.io/adrianliechti/loop-code:dind

      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:golang stacks/golang/ -f stacks/golang/Dockerfile
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:golang-dind stacks/golang/ -f stacks/golang/Dockerfile --build-arg CODE_IMAGE=ghcr.io/adrianliechti/loop-code:dind

      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:java stacks/java/ -f stacks/java/Dockerfile
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:java-dind stacks/java/ -f stacks/java/Dockerfile --build-arg CODE_IMAGE=ghcr.io/adrianliechti/loop-code:dind

  run:
    cmds:
      - docker build --tag {{.DOCKER_IMAGE}} .
      - docker build --tag {{.DOCKER_IMAGE}}:dind stacks/dind/ -f stacks/dind/Dockerfile
      - docker run -it --privileged --rm -p 3000:3000 {{.DOCKER_IMAGE}}:dind

  install:
    cmds:
      - kubectl apply -f kubernetes/*

  uninstall:
    cmds:
      - kubectl delete -f kubernetes/*
