# https://taskfile.dev

version: "3"

vars:
  DOCKER_IMAGE: adrianliechti/loop-code

tasks:
  push:
    cmds:
      - task: push-base
      - task: push-dind

  push-base:
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .

  push-dind:
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:dind dind -f dind/Dockerfile
