# https://taskfile.dev

version: "3"

vars:
  DOCKER_IMAGE: ghcr.io/adrianliechti/loop-code

  PLATFORMS: linux/arm64,linux/amd64
  EXTENSIONS: redhat.vscode-xml redhat.vscode-yaml

tasks:
  push:
    cmds:
      - docker buildx build --push --platform {{.PLATFORMS}} --tag {{.DOCKER_IMAGE}} --build-arg VSCODE_EXTENSIONS="{{.EXTENSIONS}}" .

  push-stacks:
    vars:
      STACKS:
        - { name: dotnet, base: mcr.microsoft.com/devcontainers/dotnet, ext: "muhammad-sammy.csharp" }
        - { name: golang, base: mcr.microsoft.com/devcontainers/go, ext: "golang.Go" }
        - { name: java, base: mcr.microsoft.com/devcontainers/java, ext: "redhat.java vscjava.vscode-java-debug" }
        - { name: node, base: mcr.microsoft.com/devcontainers/typescript-node, ext: "dbaeumer.vscode-eslint" }
        - { name: python, base: mcr.microsoft.com/devcontainers/python, ext: "ms-python.python ms-python.debugpy" }
    cmds:
      - for: { var: STACKS }
        cmd: |
          docker buildx build --push --platform {{.PLATFORMS}} --tag {{.DOCKER_IMAGE}}:{{.ITEM.name}} --build-arg BASE_IMAGE="{{.ITEM.base}}" --build-arg VSCODE_EXTENSIONS="{{.EXTENSIONS}} {{.ITEM.ext}}" .

  run:
    cmds:
      - docker run -it --rm -p 3000:3000 {{.DOCKER_IMAGE}}
